# Generated by Django 5.1.4 on 2025-03-21 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_user_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='count',
        ),
    ]
